### ISSUE TITLE
POSTING Data

### ISSUE THREAD

**Issue by syberkitten** [LancerComet/vue-jsonp#11]
Is it possible to send data using the POST method and not GET ?

**Comment by LancerComet** [comment]
No, because jsonp gets its data by downloading a js file.

Actually you probably don't need jsonp if you can send normal post requests, xhr is always the better way :beer:

**Comment by syberkitten** [comment]
I was under the impression this library also support standard XHR to get a JSON.
Any recommendation what to use for Vue, as i saw there is nothing that comes with it
anymore.

**Comment by LancerComet** [comment]
Axios, SuperAgent, jQuery, Request, all of them are proper libs for that stuff.

**Comment by LancerComet** [comment]
Reopen this issue if there is anything else 🍺
