### ISSUE TITLE
the script from ... was loaded even though its MIME type (“application/json”) is not a valid JavaScript MIME type.

### ISSUE THREAD

**Issue by Jones-S** [LancerComet/vue-jsonp#13]
Did you ever experience problems with the MIME type?
It does actually work but will throw this warning anyway...

I am using firefox. When doing so in Chrome, I get no warning.

I think the content type for jsonp would have to be changed somewhere, but I would not know where.
Any hint is welcome.

<img width="590" alt="image" src="https://user-images.githubusercontent.com/7059580/64193361-e719b900-ce7c-11e9-80cd-e613066cf919.png">

https://stackoverflow.com/questions/477816/what-is-the-correct-json-content-type
Says it would have to be `application/javascript` instead of `application/json`

**Comment by LancerComet** [comment]
Yes, and this incorrect `Content-Type` header is in your http response message, so this is server-side stuff, update this header's value in server-side code or somewhere.

**Comment by Jones-S** [comment]
Hm in that case that would be Mailchimp. Probably not something I can change, right?
Well. I just leave it.
Thank you.

👍🏼
