### ISSUE TITLE
Module not exporting a function

### ISSUE THREAD

**Issue by sugoidesune** [LancerComet/vue-jsonp#14]
![image](https://user-images.githubusercontent.com/20317691/70490761-92cb4880-1aff-11ea-98df-f17e61376073.png)

When importing as module in Nuxt.js there is no function defined.

**Comment by LancerComet** [comment]
Have a try on 2.0.0, it has both UMD and ESM bundles.

**Comment by step135** [comment]
The same problem in 2.0.0, it started to fail that way after upgrade to the latest version.
