### ISSUE TITLE
408 Request Timeout error with MailChimp

### ISSUE THREAD

**Issue by TomDeSmet** [LancerComet/vue-jsonp#21]
Hi,

I'm using this library to connect to MailChimp (subscribing users) but I'm getting a 408 Request Timeout error.
A little search tells me this is a client side issue. Requests with Axios to other API's work, so I'm certain it is not a local issue.

Same issue was reported in Chinese in #18 some time ago :)

**Comment by Pixelycia** [comment]
Hi, found your message while googling the same problem but their native application and I've been getting the same error (in one request from 3), this is definitely MailChimp's problem.

**Comment by gt2ming** [comment]
I also encountered this problem when using the Baidu API

**Comment by AblerSong** [comment]
don't use Promise.all(), use async await,

**Comment by vedmant** [comment]
I have the same issue, looks like it's caused by "Cross-Origin Read Blocking (CORB) blocked cross-origin response" is there any way to make it work?

**Comment by vedmant** [comment]
Actually I made it work by adding custom callback params:

```
callbackQuery: 'c',
callbackName: 'myapp',
```

**Comment by LancerComet** [comment]
In my opinion status 408 is nothing to do with the lib itself, it is due to huge payload or slow network in most cases
