### ISSUE TITLE
resolve(json) is not the latest

### ISSUE THREAD

**Issue by liliting** [LancerComet/vue-jsonp#23]
Have you ever encountered resolve (JSON), whose data is not the latest request data? 
![image](https://user-images.githubusercontent.com/23257353/113841188-0cdb1280-97c4-11eb-98de-61165a9c80ad.png)

![image](https://user-images.githubusercontent.com/23257353/113841335-2da36800-97c4-11eb-979f-cd532a7f2db2.png)

**Comment by LancerComet** [comment]
not yet, It is a little bit late but do you still face this problem?
