### ISSUE TITLE
Dealing with array params

### ISSUE THREAD

**Issue by julia817** [LancerComet/vue-jsonp#39]
```
case Array:
      value.forEach(function (item) {
        result = result.concat(formatParams(queryKey + '[]=', item))
      })
      break
```
Could you please add an optional param so that when sending Array type params, no `[]` was added here?

For example, 

```
// The request url expected to be "/some-jsonp-url?name=aaa&name=bbb&cb=jsonp_func".
jsonp('/some-jsonp-url', {
  callbackQuery: 'cb',
  callbackName: 'jsonp_func',
  name: ['aaa', 'bbb']
})
```

**Comment by LancerComet** [comment]
Sure I will add it soon

**Comment by zhushejia** [comment]
@LancerComet 
Thank you for your quick response!! Looking forward to the release :)

**Comment by julia817** [comment]
@LancerComet 
Thank you for your quick response!! Looking forward to the release :)

**Comment by LancerComet** [comment]
@julia817 I have published a beta version `2.1.0-0` to npm but it doesn't show up, which is kinda weird. If it does not show up in few hours I will just publish a new version

**Comment by LancerComet** [comment]
npm has back to normal, have a try on `2.1.0-0` or `2.1.0-1`, they are same

**Comment by julia817** [comment]
@LancerComet 
Thank you soooo much for releasing the new feature!! It works perfectly fine for me.
