### ISSUE TITLE
Callback not defined

### ISSUE THREAD

**Issue by jharmon141** [LancerComet/vue-jsonp#4]
I set up a callback function like this:

receive(data) {
    console.log(data)
}

However I still get a Reference error that receive is not defined. I click on the script and it takes me to my json response wrapped in my receive function. Is there a specific location where I should be defining this callback?

**Comment by LancerComet** [comment]
You don't need to define a callback function by yourself, just call jsonp function and vue-jsonp will handle everything.

The way how jsonp works determines that the function name must be defined in the global environment, and must be same with the one sent from server. In general, we prefer putting this process (create callback function in global enviroument) in library code to doing it by yourself.

Check it out: https://github.com/LancerComet/vue-jsonp/blob/master/src/index.js#L71

Example:

```javascript
Vue.jsonp('http://www.some-site.com/data', {
  name: 'MyName',
  age: 20,
  callbackQuery: 'cb',
  callbackName: 'receive'  // We named callback function "receive"
}).then(json => {
  // Success.
}).catch(err => {
  // Failed.
})

// Request will be sent to "http://www.some-site.com/data?name=MyName&&age=20&&cb=receive".

// And the data from server should be:
receive({ yourDataFromServer: 'Yeah!' })

// So here is no callback definition.
```
