### ISSUE TITLE
我自己不定义回调函数，超时的时候浏览器的控制台会报错：localCallback is not defined

### ISSUE THREAD

**Issue by oceans42** [LancerComet/vue-jsonp#40]
之前看到你说，不需要自己定义回调函数，正常时没问题，但超时的时候，浏览器控制台会报错：localCallback is not defined。

jsonp('xx',{
  callbackQuery: 'callback',
  callbackName: 'localCallback',
}, 35000).then(res=>{
//
}).catch(err=>{
//
})

**Comment by LancerComet** [comment]
理论上讲不应该出现，单元测试中也是使用的自定义 callbackQuery 和 callbackName，我现在认为只有一种可能性，是 window.localCallback 被提前销毁或覆盖了，能将使用环境描述的更清楚一点么

**Comment by oceans42** [comment]
是在vue2项目中使用，我设置了30分钟超时时间，偶发会超时，然后显示 localCallback is not defined

**Comment by LancerComet** [comment]
> vue2中使用，偶发会有人反馈超时，我本地复现不出来，浏览器控制台报错 localCallback is not defined。 为了实现长轮询，我是使用 setInterval 重复调用 jsonp 函数，会跟这个有关吗？ 我目前猜测是：callbackName我定义了同一个名字localCallback，没有用随机数，导致上一个请求清除 window. localCallback 时，把下一个请求生成的window. localCallback 给清除了

有可能的，这种情况下先加一个随机数上去，看看还有没有问题

**Comment by oceans42** [comment]
随机数加上去了，但是发现控制台还是偶现会报错： “jsonp_xxxxx is not defined”，而且第一次报错和第二次报错之间间隔时间刚好是我设置的 timeout 时间，第二次报错和第三次报错的间隔时间也是 timeout 时间。

**Comment by oceans42** [comment]
会不会出现这个情况，进入了catch，但是接口还在请求？

**Comment by LancerComet** [comment]
这样我就理解了，是因为在超时之后远端最终还是返回了 JSONP 的 Script，那么 Script 里的函数在执行的时候确实会找不到那个已经被回收掉的函数；因为是直接使用添加 script 的方式获取请求，因此无法像 Fetch 一样可以被 abort，而且在内部的 removeScript 函数中确实回收了 window[jsonp_xxxx] 方法，因此导致了这个报错，这个情况确实是比较极限的情况，但理论上不影响您的使用；我不知道是否应该使用 fetch 以 buffer 的形式下载完后进行处理，因为是一个极限的情况可能犯不着，但如果不修改确实有这个 Console；目前影响您的使用吗？

**Comment by oceans42** [comment]
我看请求成功的时候，会 removeScript，这就确保了进入 then 时，请求肯定终止了吧？
但是请求失败时，我看源代码，好像只有超时会 removeScript，如果非超时情况进入的 catch， 是不会 removeScript 的，也就是请求可能还在pending。

**Comment by LancerComet** [comment]
remove 一个脚本并不会直接阻止其加载过程
目前代码是只有 timeout > -1 时才会启用超时，您可以试试设置为 -1 或更小

**Comment by oceans42** [comment]
出现同时有两个请求在pending的代码：

`// 长轮询
longPolling(){
  this.timer = setInterval(()=>{
    if (this.pollState < 0) {
      this.jsonpPolling()
    }
  }, 100)
}`

`jsonpPolling(){
    this.pollState = 1; // 长轮询启动
    jsonp('xxx?times='+new Date().getTime(),{
      callbackQuery: 'callback',
    }, 1800000).then(res=>{
      this.pollState = -1; // 成功开启新的轮询
      // ...
    }).catch(err=>{
      if (err.status === 400) {
        // ...
      } else if (err.status === 408) {
        this.pollState = -1; // 超时开启新的轮询
      }
    })
  },`

**Comment by oceans42** [comment]
现在的猜测是
1、要不就是请求成功之后，还没有清除上一个，下一个就开启了。
2、超时功能有问题，并未超时，也进入408了。

我现在，成功时加了一个判断手动清除script，然后把超时时间设为-1了。

**Comment by LancerComet** [comment]
我来根据目前的情况总结一下：

1. 之前您这边不是**逻辑阻塞式**的调用，也就是说，如果一个请求被库判定超时，但网络还在 pending 状态，您会马上发起第二个请求，然后您之前的代码使用了固定的`localCallback`作为了函数名称，那么在库判定超时之后，会将 `window.localCallback` 销毁，然后这时候如果之前 pending 的请求成功，script 下载完毕后会立刻执行 `window.localCallback`，但这个时候 `localCallback` 已经不存在了，所以会报 undefined
2. 您最新的代码将超时设置为了 -1，`window.localCallback` 永远不会销毁，那么不管是之前的超时还是最新的请求，都可以顺利执行

除了设定为 -1 这个方式之外，还有一个方法是不设定 `callbackName`，让库指定随机的函数名称，这样虽然还会有 undefined 报错，但不会影响最新的请求执行
