### ISSUE TITLE
how to handle complex params?

### ISSUE THREAD

**Issue by jf3096** [LancerComet/vue-jsonp#5]
For example, how to handle object inside an array. According to ur source code, `Object.keys` then join map loop with `=` only handle first level of target params.

**Comment by LancerComet** [comment]
😂You're right, there is no support for complex objects, but you can try this:

```javascript
// This is what you want to do:
Vue.jsonp('some-url', {
  info: {
    name: 'Wow',
    age: 100
  }
})

// Try this:
Vue.jsonp('some-url', {
  'info[name]': 'Wow',
  'info[age]': 100
})
```

**Comment by yuuk** [comment]
same problem

**Comment by LancerComet** [comment]
@jf3096 @yuuk 
I have add this supporting in 0.1.7, have a look 😃
If you guys have any problem just let me know.
